name: Import issues from Template

on:
  schedule:
    - cron: '0 14 * 6 1,3,5'
    - cron: '0 14 7 6 *' 
  project:
    types: [created]
  workflow_dispatch:

jobs:
  copy:
    name: Copy Issues
    runs-on: ubuntu-latest
    steps:
      - uses: Estia-1a/projetGenieInfo_public/actions/issue-mover@issues-v2022
        with:
          destination-repo: ${{ github.repository }}
